@startuml

top to bottom direction

skinparam componentStyle uml2
skinparam handwritten false
skinparam monochrome false
skinparam shadowing false
skinparam defaultTextAlignment center
skinparam packageFontSize  14
skinparam packageFontName Arial

skinparam nodesep 20
skinparam ranksep 20
skinparam linetype polyline

skinparam component {
    StereotypeFontSize 14
    StereotypeFontColor black
    StereotypeName Arial
    StereotypeFontStyle normal
    FontSize 14
    FontColor black
    FontName Arial
    BackgroundColor white
    BorderColor black

}

skinparam package<<Transparent>> {
  borderColor Transparent
  backgroundColor Transparent
  fontColor Transparent
  stereotypeFontColor Transparent
}

!pragma ratio 0.50

left to right direction

package "%DIAGRAM_TITLE% - %date%" {

    package "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" <<Transparent>> {

        '%PACKAGES%

    }

}

@enduml


